#' Self-regulated-learning (MSLQ) responses simulated by large language models
#'
#' Five data sets of Motivated Strategies for Learning Questionnaire (MSLQ)
#' responses, each a random sample of 300 cases generated by one large language
#' model in the study *"Delving into the psychology of Machines: Exploring the
#' structure of self-regulated learning via LLM-generated survey responses"*
#' (Computers in Human Behavior, 2025). One data set per model:
#' `SRL_GPT`, `SRL_Gemini`, `SRL_Claude`, `SRL_Mistral`, and `SRL_LLaMa`.
#'
#' Only the five models whose item responses carry estimable structure are
#' included. Two other generators from the original study (ChatGPT and LeChat)
#' produced near-independent items (mean absolute inter-item correlation
#' \eqn{\approx 0.03}), so their graphical-lasso network is the empty graph;
#' they are omitted. The five retained models span the spectrum the paper
#' describes, from realistically structured (`SRL_GPT`) to strongly
#' "over-coherent" (`SRL_Gemini`, `SRL_Claude`), making the set useful for
#' demonstrating and comparing network estimators.
#'
#' @format Each is a data frame with 300 rows and 44 variables --- the 44 MSLQ
#'   items (`Q_1_IV`, `Q_2_SE`, ..., `Q_44_CSU`), each on a 1--7 Likert scale.
#'   The suffix of every item names the construct it loads on: `IV` (intrinsic
#'   value, 9 items), `SE` (self-efficacy, 9), `TA` (test anxiety, 4), `CSU`
#'   (cognitive strategy use, 13), and `SR` (self-regulation, 9). A construct
#'   composite is simply the mean of its items (see Examples).
#' @source *Delving into the psychology of Machines: Exploring the structure of
#'   self-regulated learning via LLM-generated survey responses.* Computers in
#'   Human Behavior (2025).
#'   <https://www.sciencedirect.com/science/article/pii/S074756322500216X>
#' @examples
#' # item-level partial-correlation network for one model
#' net <- ebic_glasso(SRL_GPT)
#' head(net_centralities(net))
#'
#' # aggregate the items to their five construct scores (the suffix names the
#' # construct), then compare two models' construct networks
#' scores <- function(x) vapply(
#'   split(names(x), sub("^Q_[0-9]+_", "", names(x))),
#'   function(cols) rowMeans(x[cols]), numeric(nrow(x)))
#' net_compare(scores(SRL_GPT), scores(SRL_Claude), iter = 200)
#' @name SRL
#' @keywords datasets
"SRL_GPT"

#' @rdname SRL
#' @format NULL
"SRL_Gemini"

#' @rdname SRL
#' @format NULL
"SRL_Claude"

#' @rdname SRL
#' @format NULL
"SRL_Mistral"

#' @rdname SRL
#' @format NULL
"SRL_LLaMa"
